###      Use this line to run this file   ####
## conda env create -f environment.yml
name: Final
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - tensorflow
  - keras
  - scikit-learn
  - jupyterlab
  - seaborn
  - opencv
  - pillow
  - scipy
  - h5py
  - pyyaml
  - statsmodels
  - tqdm
  - matplotlib-inline
  - pytorch  
#Use conda update --all after running this script